In [5]:
#Section A: Data Structures & Control Structures
#1 List Operations

#append
list=[1,2,3,4,5]
list.append(8)
print("append:",list)

list=[1,2,3,4,5]
list.extend([8,8])
print("extend:",list)

#insert
list=[1,2,3,4,5]
list.insert(0,1)
print("insert:",list)

#remove
list=[1,2,3,4,5]
list.remove(3)
print("remove:",list)

#pop
list=[1,2,3,4,5]
list.pop(4)
print("pop:",list)

#push
list=[1,2,3,4,5]
list.reverse()
print("reverse:",list)

#sorting
list=[7,21,9,2,29,24]
list.sort()
print("sort:",list)

#count
list=[8,12,3,4,5]
list.count(10)
print("count:",list)

#index
list=[2,4,6,9,10]
list.index(6)
print("index:",list)

#clear
number_list=list.copy()
number_list.clear()
print("clear:",number_list)

append: [1, 2, 3, 4, 5, 8]
extend: [1, 2, 3, 4, 5, 8, 8]
insert: [1, 1, 2, 3, 4, 5]
remove: [1, 2, 4, 5]
pop: [1, 2, 3, 4]
reverse: [5, 4, 3, 2, 1]
sort: [2, 7, 9, 21, 24, 29]
count: [8, 12, 3, 4, 5]
index: [2, 4, 6, 9, 10]
clear: []


In [14]:
# 2 tuple Example

students=('priyanka','satwik','pavan')
print("original Tuple:",students)

#trying to change secong name
students[1]='priya'
print(students)

#output : TypeError --'tuple' object does not support item assignment 

Because tuples are immutable in python. Immutable means values cannot be changed,
added, or removed after creation and therefore, changing the second name gives an error.


original Tuple: ('priyanka', 'satwik', 'pavan')


TypeError: 'tuple' object does not support item assignment

In [15]:
#3 Set with duplicate values

set={1,2,3,4,5,2,1,3,4,3,6}
print("Set output:",set)

Output Explanation : Duplicates values are automatically removed in sets. It does not 
contains duplicates values.

Set output: {1, 2, 3, 4, 5, 6}


In [18]:
# 4 Dictionary Operations

detailes = {"name":"priyanka", "age":22, "city": "Hyderabad"}
print("1 st values :",detailes)

#updated age

detailes["age"]=21
print("updated age:",detailes)

#add email

detailes["email"]="Excelr@gmail.com"
print("Add the email:",detailes)

1 st values : {'name': 'priyanka', 'age': 22, 'city': 'Hyderabad'}
updated age: {'name': 'priyanka', 'age': 21, 'city': 'Hyderabad'}
Add the email: {'name': 'priyanka', 'age': 21, 'city': 'Hyderabad', 'email': 'Excelr@gmail.com'}


In [20]:
# 5 Eligible to vote (age ≥ 18)

age=int(input("Enter age:"))
if age > 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter age: 19


Eligible to vote


In [22]:
# 6 Grade Calculation

marks=int(input("Enter the marks:"))
if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("fail")

Enter the marks: 79


Grade B


In [31]:
# 7 Positive and Even check

number=int(input("Enter number:"))
if number > 0:
    print("Positive number")

    if number % 2 == 0:
        print("It is also even")
    else:
        print("It is odd")
elif number == 0:
    print("Number is zero")
else:
    print("Negative Number")



Enter number: 13


Positive number
It is odd


In [41]:
# Section B: Numpy
#Scaler

import numpy as np
scalar=np.array(10)
print("Scalar:",scalar)

#1D array

array1=np.array([1,2,3,4,5,6])
print("1D array:",array1)

#2D array

array2=np.array([[1,2,3],
                [1,2,3]])
print("2D array:",array2)

Scalar: 10
1D array: [1 2 3 4 5 6]
2D array: [[1 2 3]
 [1 2 3]]


In [40]:
# 9 Random Integer Array

Random_array=np.random.randint(0,100,(4,4))
print("4*4 Random Array:",Random_array)

4*4 Random Array: [[53 47 46 44]
 [16 97 67 48]
 [ 6 71 85 20]
 [60 54 74 48]]


In [48]:
# 10 Convert numpy array to pandas dataframe

import pandas as pd
numpy_array=np.array([[1,2,3],
                      [2,3,1],
                      [3,2,1]])
df=pd.DataFrame(numpy_array,columns=['A','B','C'])
print("DataFrame:",df)

DataFrame:    A  B  C
0  1  2  3
1  2  3  1
2  3  2  1


In [45]:
# Section C: Exploring Pandas

import pandas as pd
import numpy as np

data = {
    "Name": ["Priya", "Rahul", "Sneha", "Kiran", "Anu","Pavan", "Teja", "Ravi", "Divya", "Sneha"],

    "Age": [21, 22, 23, 24, 25,26, 27, 28, 29, 23],

    "City": ["Hyderabad", "Vizag", "Chennai", "Delhi", "Mumbai","Pune", "Goa", "Bangalore", "Kolkata", "Chennai"],

    "Salary": [25000, 30000, np.nan, 40000, 35000,45000, np.nan, 50000, 55000, np.nan]
}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)

# info()
print("DataFrame Info:")
print(df.info())

# describe()
print("Describe:")
print(df.describe())

# Select Name and City columns
print("Selected Columns:")
print(df[['Name', 'City']])

# Drop City column
df_drop = df.drop('City', axis=1)
print("After Dropping City Column:")
print(df_drop)

# Fill missing values 
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print("After Filling Missing Values:")
print(df)

# Remove duplicate rows
df = df.drop_duplicates()
print("After Removing Duplicate Rows:")
print(df)

DataFrame:
    Name  Age       City   Salary
0  Priya   21  Hyderabad  25000.0
1  Rahul   22      Vizag  30000.0
2  Sneha   23    Chennai      NaN
3  Kiran   24      Delhi  40000.0
4    Anu   25     Mumbai  35000.0
5  Pavan   26       Pune  45000.0
6   Teja   27        Goa      NaN
7   Ravi   28  Bangalore  50000.0
8  Divya   29    Kolkata  55000.0
9  Sneha   23    Chennai      NaN
DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
Describe:
            Age        Salary
count  10.00000      7.000000
mean   24.80000  40000.000000
std     2.65832  10801.234497
min    21.00000  25000.000000
25%    23.00000  32500.000000
50%    24.5000